security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:       [ROLE_ADMIN,ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_SUPER_ADMIN,ROLE_ADMIN,ROLE_USER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            remember_me:
                secret: '%secret%'
            pattern: ^/
            form_login:
                provider: fos_userbundle
                
            logout:       true
            anonymous:    true
            logout_on_user_change: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/resetting, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/profile/change-password, role: ROLE_USER }
        